"""
Operating System (IT-508) -- Previous Year Question Answers
UIT-RGPV (Autonomous) Bhopal | Semester V
Covers: May-June 2024, May-June 2025, July-Dec 2024, Dec 2022
Run:    python os_pyq.py
Output: OS_PYQ_Answers.pdf
"""

from __future__ import annotations

import paperforge_notes as pn
import paperforge_diagrams as pd

# =============================================================================
#  THEME & GLOBAL FOOTER
# =============================================================================
pn.set_story([])
pn.set_theme(pn.DARK)

pn.set_global_footer(
    left="Operating System (IT-508) -- PYQ Answers",
    right="UIT-RGPV (Autonomous) Bhopal",
    show_page_num=True,
)

diag_theme = pd.DiagramTheme.from_notes_theme(pn.get_theme())

# =============================================================================
#  COVER PAGE
# =============================================================================
pn.bookmark("Cover Page")
pn.suppress_footer(page_only=True)
pn.sp(22)

pn.cover_card(
    "OPERATING SYSTEM (IT-508)",
    "Previous Year Questions & Model Answers",
)
# pn.cover_subtitle(
#     [
#         "UIT-RGPV (Autonomous) Bhopal  |  Semester V  |  Subject Code: IT-508",
#         "Exam Papers Covered: May-June 2024  |  May-June 2025  |  July-Dec 2024  |  Dec 2022",
#         "All 5 Questions with Comprehensive Model Answers, Diagrams, Code & Solved Numericals",
#     ]
# )
pn.sp(8)
pn.rule(pn.get_theme().rl(pn.get_theme().accent), 1.5)
pn.sp(6)

pn.info_table(
    ["Question", "Topic Area", "Key Sub-Parts Covered"],
    [
        [
            "Q1",
            "OS Fundamentals & Process Management",
            "Software types, System calls, Process states, PCB, Context switch, "
            "Traps vs Interrupts, RPC, OS services, Multiprocessing, Schedulers",
        ],
        [
            "Q2",
            "CPU Scheduling & Synchronization",
            "Semaphores, IPC, Shared memory vs message passing, Schedulers, "
            "Critical section, FCFS/SJF/RR Gantt charts, Bounded Buffer",
        ],
        [
            "Q3",
            "Deadlock & Memory Management",
            "Deadlock conditions, Banker's Algorithm, RAG, Fragmentation, "
            "Logical vs Physical address, Peterson's solution, First Fit/Worst Fit",
        ],
        [
            "Q4",
            "Virtual Memory & Paging",
            "Paging, Segmentation, TLB, Thrashing, Demand Paging, "
            "FIFO/LRU/Optimal page replacement solved numericals",
        ],
        [
            "Q5",
            "File & Disk Management",
            "File attributes/ops, Directory types, Allocation methods, "
            "FCFS/C-SCAN/SSTF disk scheduling solved numericals, Free space mgmt",
        ],
    ],
    col_widths=["10%", "28%", "62%"],
)

pn.sp(6)
pn.note(
    "Mark scheme: Part (a) = 3 marks | Part (b) = 4 marks | Part (c) = 4 marks | "
    "Part (d) = 10 marks | Part (e) = 10 marks (alternative). "
    "Questions appearing across multiple exam years are consolidated into ONE comprehensive answer."
)
pn.br()

# =============================================================================
#  TABLE OF CONTENTS
# =============================================================================
pn.suppress_footer(page_only=True)
pn.toc()

# #############################################################################
#  QUESTION 1 -- OS FUNDAMENTALS & PROCESS MANAGEMENT
# #############################################################################
pn.part_box("QUESTION 1 -- OS FUNDAMENTALS & PROCESS MANAGEMENT")

# -----------------------------------------------------------------------------
#  Q1(a) -- 3 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q1(a) [3 Marks] -- Traps vs Interrupts | Software Types | Process States\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024 | May-June 2025)"
)

pn.section("Traps vs Interrupts")
pn.definition(
    "<b>Interrupt:</b> A hardware-generated signal sent to the CPU by an external device "
    "(keyboard, disk, timer, NIC) to notify the OS that an event requiring attention has occurred. "
    "Interrupts are <b>asynchronous</b> — they occur independently of the currently executing instruction. "
    "When an interrupt occurs, the CPU finishes the current instruction, saves its state, "
    "and jumps to the Interrupt Service Routine (ISR)."
)
pn.definition(
    "<b>Trap (Software Interrupt):</b> A <b>synchronous</b> signal generated by the CPU itself "
    "due to an exceptional condition in the executing program. Traps are caused by: "
    "(1) System calls (user program requesting OS service), "
    "(2) Program errors (division by zero, invalid memory access, overflow), "
    "(3) Deliberate software interrupts (INT instruction in x86)."
)
pn.info_table(
    ["Aspect", "Interrupt", "Trap (Software Interrupt)"],
    [
        ["Source", "External hardware device", "CPU / executing program"],
        [
            "Nature",
            "Asynchronous (unpredictable)",
            "Synchronous (instruction-triggered)",
        ],
        [
            "Cause",
            "I/O completion, timer tick, hardware event",
            "System call, error, deliberate INT",
        ],
        [
            "Example",
            "Keyboard press, disk I/O done, network packet",
            "Division by zero, page fault, system call",
        ],
        [
            "Handler",
            "Interrupt Service Routine (ISR)",
            "Trap handler / exception handler",
        ],
        ["Occurrence", "Can happen any time", "Always tied to a specific instruction"],
    ],
)
pn.exam(
    "Exam tip: The KEY difference is hardware vs software origin, and asynchronous vs synchronous. "
    "Traps are always caused by the running program itself. Interrupts come from outside the CPU."
)

pn.section("Software Types (May-June 2025)")
pn.info_table(
    ["Category", "Description", "Examples"],
    [
        [
            "System Software",
            "Programs that manage hardware and provide a platform for other software.",
            "OS (Windows, Linux), Device Drivers, BIOS/UEFI",
        ],
        [
            "Application Software",
            "Programs designed for end-users to perform specific tasks.",
            "MS Word, Chrome, VLC, Games, Tally",
        ],
        [
            "Utility Software",
            "Tools for maintaining, configuring, or optimizing the computer.",
            "Antivirus, Disk Cleanup, WinRAR, Task Manager",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q1(b) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q1(b) [4 Marks] -- Process State Diagram | PCB | System Call Definition\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024 | May-June 2025)"
)

pn.section("Process State Transition Diagram")
pn.definition(
    "<b>Process State:</b> A process moves through several states during its lifetime. "
    "The OS tracks these states in the Process Control Block (PCB) and uses them for scheduling."
)
pn.bullet(
    [
        "<b>New:</b> Process is being created (OS allocating resources, PCB being built).",
        "<b>Ready:</b> Process is in memory and waiting to be assigned to the CPU. May be many processes here.",
        "<b>Running:</b> Instructions are being executed by the CPU. Only ONE process per CPU core.",
        "<b>Waiting (Blocked):</b> Process is waiting for an I/O event or signal to complete.",
        "<b>Terminated:</b> Process has finished execution. OS deallocates its resources.",
    ]
)
pn.info_table(
    ["Transition", "Trigger"],
    [
        ["New → Ready", "OS admits the process (memory allocated, PCB created)"],
        ["Ready → Running", "CPU scheduler dispatches the process (context switch)"],
        [
            "Running → Waiting",
            "Process requests I/O or waits for an event (e.g., read from disk)",
        ],
        ["Waiting → Ready", "I/O completes or event occurs (interrupt from device)"],
        [
            "Running → Ready",
            "Preempted by scheduler (time quantum expired) or higher-priority process arrives",
        ],
        ["Running → Terminated", "Process executes exit() system call or is killed"],
    ],
)

# Process state diagram using Flowchart
sm_proc = pd.StateMachine(
    width=pn.CW,
    height=260,
    theme=diag_theme,
    caption="Fig 1.1: Five-State Process Model — State Transition Diagram",
)
sm_proc.state("new", "New", x=80, y=160, initial=True)
sm_proc.state("ready", "Ready", x=220, y=160)
sm_proc.state("running", "Running", x=370, y=160)
sm_proc.state("waiting", "Waiting\n(Blocked)", x=295, y=50)
sm_proc.state("term", "Terminated", x=500, y=160, accepting=True)

sm_proc.transition("new", "ready", label="admitted\n(long-term scheduler)", pill=True)
sm_proc.transition(
    "ready", "running", label="dispatch\n(short-term scheduler)", offset=15.0, pill=True
)
sm_proc.transition(
    "running",
    "ready",
    label="interrupt /\ntime quantum expired",
    offset=15.0,
    pill=True,
)
sm_proc.transition("running", "waiting", label="I/O or\nevent wait", pill=True)
sm_proc.transition(
    "waiting", "ready", label="I/O complete /\nevent occurred", pill=True
)
sm_proc.transition("running", "term", label="exit()", pill=True)
pn.story.extend(sm_proc.as_flowable())

pn.section("Process Control Block (PCB)")
pn.definition(
    "<b>PCB (Process Control Block):</b> A data structure maintained by the OS for each process. "
    "It is the repository of all information about a process. When a context switch occurs, "
    "the CPU state is saved into the PCB of the outgoing process and restored from the PCB of the incoming one."
)
pn.info_table(
    ["PCB Field", "Contents / Purpose"],
    [
        ["Process ID (PID)", "Unique integer identifier assigned by the OS"],
        ["Process State", "Current state: New, Ready, Running, Waiting, Terminated"],
        ["Program Counter (PC)", "Address of the NEXT instruction to execute"],
        [
            "CPU Registers",
            "All register values: accumulator, index, stack pointer, general-purpose",
        ],
        [
            "CPU Scheduling Info",
            "Priority, scheduling queue pointers, time slice remaining",
        ],
        [
            "Memory Management Info",
            "Base/limit registers, page table pointer, segment table",
        ],
        [
            "I/O Status Info",
            "List of open files, pending I/O requests, allocated I/O devices",
        ],
        [
            "Accounting Info",
            "CPU time used, time limits, account numbers, job/process numbers",
        ],
    ],
)

pn.section("System Call — Definition (May-June 2025)")
pn.definition(
    "<b>System Call:</b> The programmatic interface by which a user-mode application requests "
    "a service from the OS kernel. System calls are the ONLY way for user programs to cross "
    "from user mode into kernel mode. Examples: <code>read()</code>, <code>write()</code>, "
    "<code>fork()</code>, <code>exit()</code>."
)

# -----------------------------------------------------------------------------
#  Q1(c) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q1(c) [4 Marks] -- Context Switching | Remote Procedure Call | Critical Section\n"
    "(May-June 2024 | July-Dec 2024 | May-June 2025)"
)

pn.section("Context Switching")
pn.definition(
    "<b>Context Switch:</b> The process of saving the state (context) of the currently running "
    "process and restoring the saved state of the next scheduled process. "
    "Context switching is <b>pure overhead</b> — no user-useful work is done during the switch. "
    "Typical context switch time: 1–10 microseconds."
)
pn.bullet(
    [
        "<b>Step 1:</b> Save current process state into its PCB (PC, registers, stack pointer, memory maps).",
        "<b>Step 2:</b> Update PCB state from Running → Ready or Waiting.",
        "<b>Step 3:</b> Select next process to run via CPU scheduler.",
        "<b>Step 4:</b> Load the new process's PCB (restore PC, registers, memory maps).",
        "<b>Step 5:</b> Resume execution of the new process from where it left off.",
    ]
)

pn.section("Remote Procedure Call (RPC) — July-Dec 2024")
pn.definition(
    "<b>RPC (Remote Procedure Call):</b> An IPC mechanism that allows a program on one machine "
    "to call a procedure (function) on another machine over a network as if it were a local call. "
    "The calling program is unaware of the network communication details."
)
pn.info_table(
    ["Step", "Action"],
    [
        [
            "1. Client calls stub",
            "Client program calls a local stub procedure with normal arguments",
        ],
        [
            "2. Stub marshals",
            "Stub packages arguments into a network message (marshalling)",
        ],
        ["3. Network send", "Message is sent over the network to the server machine"],
        [
            "4. Server stub unmarshals",
            "Server-side stub unpacks the message and calls the real procedure",
        ],
        [
            "5. Procedure executes",
            "The actual server procedure runs and produces a result",
        ],
        [
            "6. Result returned",
            "Result is marshalled, sent back, and returned to the client caller",
        ],
    ],
)

pn.section("Critical Section Requirements — May-June 2025")
pn.definition(
    "<b>Critical Section:</b> A section of code where a process accesses shared resources "
    "(shared memory, files, hardware). Only ONE process should be in its critical section at a time."
)
pn.info_table(
    ["Requirement", "Meaning"],
    [
        [
            "1. Mutual Exclusion",
            "If process Pi is in its CS, no other process Pj can be in its CS simultaneously.",
        ],
        [
            "2. Progress",
            "If no process is in the CS and some processes wish to enter, only those not in the remainder section can decide who enters next, and this selection cannot be postponed indefinitely.",
        ],
        [
            "3. Bounded Waiting",
            "There exists a bound on the number of times other processes can enter their CS after a process has requested to enter its CS and before its request is granted.",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q1(d) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q1(d) [10 Marks] -- System Calls with Examples | OS Functions & Services\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024)"
)

pn.section("System Calls — Detailed Explanation")
pn.definition(
    "<b>System Call:</b> The mechanism that provides the interface between a running program "
    "and the OS. When a user program needs to perform a privileged operation (like reading a file, "
    "creating a process, or allocating memory), it makes a system call. "
    "The OS kernel handles the request in kernel mode and returns the result."
)

pn.section("How System Calls Work")
pn.bullet(
    [
        "<b>User program</b> invokes a library wrapper (e.g., <code>fread()</code> in C standard library).",
        "<b>Library</b> places the system call number and arguments in CPU registers.",
        "<b>TRAP instruction</b> (INT 0x80 / SYSCALL) switches CPU to kernel mode.",
        "<b>Kernel</b> looks up the system call table using the call number.",
        "<b>Kernel handler</b> executes the requested service.",
        "<b>Result</b> is placed in a register; CPU returns to user mode (IRET / SYSRET).",
    ]
)

pn.section("Categories of System Calls with Examples")
pn.info_table(
    ["Category", "Purpose", "Linux Examples", "Windows Examples"],
    [
        [
            "Process Control",
            "Create, terminate, execute, wait for processes",
            "fork(), exec(), exit(), wait()",
            "CreateProcess(), TerminateProcess()",
        ],
        [
            "File Manipulation",
            "Create, open, read, write, delete files",
            "open(), read(), write(), close(), unlink()",
            "CreateFile(), ReadFile(), WriteFile()",
        ],
        [
            "Device Management",
            "Request/release devices, read/write device data",
            "ioctl(), read(), write() on /dev",
            "DeviceIoControl()",
        ],
        [
            "Information Maintenance",
            "Get/set time, date, system info, process attributes",
            "getpid(), getuid(), alarm(), time()",
            "GetSystemTime(), GetProcessId()",
        ],
        [
            "Communication (IPC)",
            "Create channels, send/receive messages, shared memory",
            "pipe(), socket(), send(), recv(), shmget()",
            "CreatePipe(), SendMessage()",
        ],
        [
            "Protection",
            "Set/get permissions, file access rights",
            "chmod(), chown(), setuid()",
            "SetFileSecurity(), GetUserName()",
        ],
    ],
)

pn.section("System Call Example in C")
pn.code_block(
    """/* File I/O using system calls */
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main() {
    int fd;
    char buffer[128];
    ssize_t bytes_read;

    /* open() system call -- open file, returns file descriptor */
    fd = open("data.txt", O_RDONLY);
    if (fd < 0) {
        perror("open failed");
        return 1;
    }

    /* read() system call -- read up to 128 bytes into buffer */
    bytes_read = read(fd, buffer, sizeof(buffer) - 1);
    if (bytes_read > 0) {
        buffer[bytes_read] = '\\0';
        printf("Read: %s\\n", buffer);
    }

    /* close() system call -- release the file descriptor */
    close(fd);
    return 0;
}""",
    lang="c",
)

pn.section("Major Functions and Services of an OS")
pn.info_table(
    ["Function", "Description"],
    [
        [
            "Process Management",
            "Create/delete processes, scheduling, synchronization, deadlock handling.",
        ],
        [
            "Memory Management",
            "Allocate/deallocate memory, paging, segmentation, virtual memory.",
        ],
        [
            "File System Management",
            "Create/delete files and directories, map files to disk blocks, access control.",
        ],
        [
            "I/O System Management",
            "Buffering, caching, device drivers, uniform I/O interface.",
        ],
        [
            "Secondary Storage",
            "Free space management, disk scheduling, storage allocation.",
        ],
        [
            "Security & Protection",
            "User authentication, process isolation, access control lists.",
        ],
        ["Networking", "TCP/IP stack, socket API for network communication."],
        [
            "Command Interpreter",
            "Shell that reads and executes user commands (bash, cmd.exe).",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q1(e) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q1(e) [10 Marks] -- Multiprocessing Advantages & Types | Scheduler Types\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024 | May-June 2025)"
)

pn.section("Advantages of Multiprocessing Systems")
pn.bullet(
    [
        "<b>Increased Throughput:</b> Multiple CPUs execute multiple processes simultaneously, "
        "dramatically increasing the number of tasks completed per unit time.",
        "<b>Economy of Scale:</b> Multiprocessor systems are cheaper per MIPS (million instructions/sec) "
        "than multiple separate single-processor systems sharing peripherals.",
        "<b>Increased Reliability / Fault Tolerance:</b> If one processor fails, the remaining processors "
        "can continue running. Graceful degradation rather than total failure.",
        "<b>Better Resource Utilization:</b> While one CPU handles I/O-intensive tasks, others handle "
        "compute-intensive tasks, maximizing overall hardware utilization.",
        "<b>Scalability:</b> Additional processors can be added to increase computational power without "
        "redesigning the entire system.",
    ]
)

pn.section("Types of Multiprocessor Systems")
pn.info_table(
    ["Type", "Description", "Memory", "Example"],
    [
        [
            "Symmetric Multiprocessing (SMP)",
            "All processors are equal peers. Each runs its own copy of OS or shares one OS. "
            "All processors have equal access to memory.",
            "Shared memory",
            "Modern multi-core PCs, Linux SMP",
        ],
        [
            "Asymmetric Multiprocessing (AMP)",
            "One master processor controls the system and assigns tasks to slave processors. "
            "Only master runs OS; slaves run user tasks.",
            "Shared memory",
            "Early multiprocessor systems",
        ],
        [
            "Non-Uniform Memory Access (NUMA)",
            "Each processor has local fast memory and can access remote memory (other CPUs') "
            "at higher latency. Scalable for many CPUs.",
            "Distributed shared",
            "AMD EPYC servers, large server systems",
        ],
        [
            "Clustered Systems",
            "Multiple complete computer systems connected via LAN or high-speed interconnect, "
            "working together as one system.",
            "Distributed",
            "High-performance computing clusters, Beowulf clusters",
        ],
    ],
)

pn.section("Types of Schedulers (May-June 2025)")
pn.info_table(
    ["Scheduler", "Also Called", "Frequency", "Role"],
    [
        [
            "Long-Term Scheduler",
            "Job Scheduler / Admission Scheduler",
            "Infrequent (seconds to minutes)",
            "Decides which processes are admitted to the ready queue from the job pool. "
            "Controls the degree of multiprogramming (how many processes are in memory).",
        ],
        [
            "Short-Term Scheduler",
            "CPU Scheduler / Dispatcher",
            "Very frequent (milliseconds)",
            "Selects which ready process gets the CPU next. Runs after every interrupt, "
            "system call, or time quantum expiry. Most performance-critical scheduler.",
        ],
        [
            "Medium-Term Scheduler",
            "Swapper",
            "Moderate (seconds)",
            "Manages swapping: removes processes from memory to disk (swap out) to reduce "
            "the degree of multiprogramming, and brings them back (swap in) when memory is available.",
        ],
    ],
)

# #############################################################################
#  QUESTION 2 -- CPU SCHEDULING & SYNCHRONIZATION
# #############################################################################
pn.part_box("QUESTION 2 -- CPU SCHEDULING & PROCESS SYNCHRONIZATION")

# -----------------------------------------------------------------------------
#  Q2(a) -- 3/4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q2(a) [3/4 Marks] -- Semaphore Concept | IPC Examples | Process Structure\n"
    "(May-June 2024 | Dec 2022 | May-June 2025 | July-Dec 2024)"
)

pn.section("Process Structure in Memory (July-Dec 2024)")
pn.definition(
    "<b>Process Structure:</b> A process is a program in execution. The OS represents the "
    "process in memory by dividing its allocated address space into several distinct logical segments:"
)
pn.bullet(
    [
        "<b>Text Section (Code):</b> Contains the compiled machine instructions read from disk. Usually read-only to prevent accidental modification.",
        "<b>Data Section:</b> Stores global and static variables. Divided into Initialized Data (pre-set in variables) and Uninitialized Data (BSS - Block Started by Symbol, set to zero at start).",
        "<b>Heap:</b> Dynamically allocated memory at runtime (using <code>malloc()</code> or <code>new</code>). It grows upward toward higher memory addresses.",
        "<b>Stack:</b> Temporary scratchpad for function execution. Stores local variables, function parameters, and return addresses. It grows downward toward lower memory addresses.",
    ]
)

stack_proc = pd.LayeredStack(
    width=pn.CW * 0.55,
    height=200,
    theme=diag_theme,
    caption="Fig 2.0: Process Structure in Memory Layout",
)
stack_proc.layer("Stack", sublabel="Local variables, function frames (grows downward)")
stack_proc.layer(
    "↓  Free Memory  ↑", sublabel="Dynamic address space shared by Stack & Heap"
)
stack_proc.layer("Heap", sublabel="Dynamically allocated memory (grows upward)")
stack_proc.layer("Data (Initialized & BSS)", sublabel="Global and static variables")
stack_proc.layer("Text (Code)", sublabel="Executable program code (read-only)")
pn.story.extend(stack_proc.as_flowable())

pn.section("Semaphore Concept")
pn.definition(
    "<b>Semaphore:</b> A synchronization primitive proposed by Dijkstra (1965). "
    "A semaphore <code>S</code> is an integer variable that is accessed only through "
    "two standard atomic operations: <b>wait(S)</b> (also called P or down) and "
    "<b>signal(S)</b> (also called V or up). The OS guarantees these operations are atomic "
    "(indivisible) — no context switch occurs in the middle of wait/signal."
)
pn.code_block(
    """/* Semaphore Operations -- OS guarantees these are ATOMIC */

wait(S) {           /* Also called: P(S), down(S) */
    while (S <= 0)
        ;           /* Busy-wait (spinlock) -- CPU keeps checking */
    S--;            /* Decrement: consume one resource/permit */
}

signal(S) {         /* Also called: V(S), up(S) */
    S++;            /* Increment: release one resource/permit */
}

/* BINARY SEMAPHORE (mutex): S initialized to 1
   Used for mutual exclusion -- only 1 process in critical section */

/* COUNTING SEMAPHORE: S initialized to N (resource count)
   Used to manage N instances of a resource */""",
    lang="c",
)

pn.section("IPC Real-Life Examples (May-June 2025)")
pn.info_table(
    ["Scenario", "IPC Mechanism Used", "Explanation"],
    [
        [
            "Web browser + renderer process",
            "Message Passing (IPC sockets/pipes)",
            "The browser's UI process and the page renderer process communicate via OS message passing — they do not share memory for security isolation.",
        ],
        [
            "Producer-Consumer (print spooler)",
            "Shared Memory + Semaphore",
            "A producer process writes documents to a shared spooler buffer in shared memory. The printer daemon (consumer) reads from it. Semaphores synchronize access.",
        ],
        [
            "Shell pipeline: ls | grep txt",
            "Pipe (anonymous)",
            "The shell creates a pipe. stdout of ls is connected to stdin of grep via the pipe file descriptor — classic unidirectional IPC.",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q2(b) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q2(b) [4 Marks] -- Schedulers (Short/Medium/Long) | Shared Memory vs Message Passing\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024 | May-June 2025)"
)

pn.section("Role of Long-Term, Medium-Term & Short-Term Schedulers")
pn.info_table(
    ["Scheduler", "Frequency", "Decision", "Impact"],
    [
        [
            "Long-Term (Job Scheduler)",
            "Infrequent — seconds to minutes",
            "Which jobs from the disk job pool are loaded into main memory (admitted to ready queue)",
            "Controls degree of multiprogramming. Selects a good mix of CPU-bound and I/O-bound jobs.",
        ],
        [
            "Short-Term (CPU Scheduler)",
            "Very frequent — every few ms",
            "Which ready process gets CPU next",
            "Directly affects response time and throughput. Uses scheduling algorithms (FCFS, SJF, RR, Priority).",
        ],
        [
            "Medium-Term (Swapper)",
            "Moderate — seconds",
            "Which processes are swapped out to disk and which are swapped back in",
            "Reduces degree of multiprogramming temporarily to free memory. Improves process mix.",
        ],
    ],
)

pn.section("Shared Memory vs Message Passing")
pn.info_table(
    ["Feature", "Shared Memory", "Message Passing"],
    [
        [
            "Mechanism",
            "Processes share a common region of physical/virtual memory",
            "Processes exchange data via send() and receive() primitives",
        ],
        [
            "Speed",
            "Fast — no kernel involvement after setup",
            "Slower — each message requires kernel system calls",
        ],
        [
            "Synchronization",
            "Must be handled explicitly by user (semaphores, mutexes)",
            "Implicitly handled by OS message queue",
        ],
        [
            "Complexity",
            "Complex — programmer manages race conditions",
            "Simpler — OS handles coordination",
        ],
        [
            "Suitability",
            "Same machine, large data transfers",
            "Distributed systems, different machines",
        ],
        ["Example", "POSIX shmget(), mmap()", "POSIX mq_send(), message queues, pipes"],
    ],
)

# -----------------------------------------------------------------------------
#  Q2(c) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q2(c) [4 Marks] -- CPU Scheduling Criteria | Preemptive vs Non-Preemptive\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024)"
)

pn.section("CPU Scheduling Criteria")
pn.info_table(
    ["Criterion", "Definition", "Goal"],
    [
        [
            "CPU Utilization",
            "Percentage of time CPU is busy executing user processes",
            "Maximize (target: 40-90%)",
        ],
        ["Throughput", "Number of processes completed per unit time", "Maximize"],
        [
            "Turnaround Time",
            "Total time from process submission to completion (WT + Burst + I/O)",
            "Minimize",
        ],
        [
            "Waiting Time",
            "Total time spent in the ready queue waiting for CPU",
            "Minimize",
        ],
        [
            "Response Time",
            "Time from submission until the FIRST response is produced",
            "Minimize (for interactive systems)",
        ],
    ],
)

pn.section("Preemptive vs Non-Preemptive Scheduling")
pn.info_table(
    ["Aspect", "Non-Preemptive", "Preemptive"],
    [
        [
            "CPU Release",
            "Process voluntarily releases CPU (I/O wait or termination only)",
            "OS can forcibly take CPU away from a running process",
        ],
        [
            "Context Switch",
            "Only at I/O or exit — infrequent",
            "Can happen at any time — more frequent",
        ],
        [
            "Response Time",
            "Poor for interactive tasks",
            "Better response time for interactive systems",
        ],
        [
            "Overhead",
            "Low scheduling overhead",
            "Higher overhead due to frequent context switches",
        ],
        [
            "Examples",
            "FCFS, Non-Preemptive SJF, HRRN",
            "Round Robin, SRTF, Preemptive Priority",
        ],
        [
            "Risk",
            "CPU hogging by long processes",
            "Race conditions on shared data — needs synchronization",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q2(d) -- 10 Marks: Scheduling Numericals
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q2(d) [10 Marks] -- Gantt Charts & Average Waiting Time: FCFS, SJF, Round Robin (q=1)\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024)"
)

pn.section(
    "Problem: Processes {A:BT=3,AT=2}, {B:BT=5,AT=1}, {C:BT=2,AT=4}, {D:BT=5,AT=0}, {E:BT=5,AT=3}"
)
pn.info_table(
    ["Process", "Arrival Time (AT)", "Burst Time (BT)"],
    [
        ["A", "2", "3"],
        ["B", "1", "5"],
        ["C", "4", "2"],
        ["D", "0", "5"],
        ["E", "3", "5"],
    ],
)

pn.section("(i) FCFS — First Come First Served")
pn.body(
    "FCFS is non-preemptive. Processes execute in order of arrival time. "
    "Order: D(AT=0), B(AT=1), A(AT=2), E(AT=3), C(AT=4)"
)
pn.info_table(
    [
        "Process",
        "Start Time",
        "End Time",
        "Turnaround Time (TAT = End - AT)",
        "Waiting Time (WT = TAT - BT)",
    ],
    [
        ["D", "0", "5", "5 - 0 = 5", "5 - 5 = 0"],
        ["B", "5", "10", "10 - 1 = 9", "9 - 5 = 4"],
        ["A", "10", "13", "13 - 2 = 11", "11 - 3 = 8"],
        ["E", "13", "18", "18 - 3 = 15", "15 - 5 = 10"],
        ["C", "18", "20", "20 - 4 = 16", "16 - 2 = 14"],
    ],
)
pn.note(
    "FCFS Gantt Chart: | D (0-5) | B (5-10) | A (10-13) | E (13-18) | C (18-20) |\n"
    "Average Waiting Time = (0 + 4 + 8 + 10 + 14) / 5 = 36 / 5 = <b>7.2 ms</b>\n"
    "Average Turnaround Time = (5 + 9 + 11 + 15 + 16) / 5 = 56 / 5 = <b>11.2 ms</b>"
)

pn.section("(ii) SJF — Shortest Job First (Non-Preemptive)")
pn.body(
    "At each selection point (when a process finishes), select the process with the shortest burst time among all arrived processes."
)
pn.info_table(
    [
        "Time",
        "Decision Point",
        "Available Processes (arrived)",
        "Chosen Process (shortest BT)",
    ],
    [
        ["t=0", "D starts", "D (AT=0, BT=5) only", "D (BT=5)"],
        ["t=5", "D finishes", "A(BT=3), B(BT=5), C(BT=2), E(BT=5)", "C (BT=2)"],
        ["t=7", "C finishes", "A(BT=3), B(BT=5), E(BT=5)", "A (BT=3)"],
        [
            "t=10",
            "A finishes",
            "B(BT=5), E(BT=5)",
            "B (BT=5) -- tie-breaker by arrival time",
        ],
        ["t=15", "B finishes", "E(BT=5)", "E (BT=5)"],
    ],
)
pn.info_table(
    [
        "Process",
        "Start Time",
        "End Time",
        "Turnaround Time (TAT = End - AT)",
        "Waiting Time (WT = TAT - BT)",
    ],
    [
        ["D", "0", "5", "5 - 0 = 5", "5 - 5 = 0"],
        ["C", "5", "7", "7 - 4 = 3", "3 - 2 = 1"],
        ["A", "7", "10", "10 - 2 = 8", "8 - 3 = 5"],
        ["B", "10", "15", "15 - 1 = 14", "14 - 5 = 9"],
        ["E", "15", "20", "20 - 3 = 17", "17 - 5 = 12"],
    ],
)
pn.note(
    "SJF Gantt Chart: | D (0-5) | C (5-7) | A (7-10) | B (10-15) | E (15-20) |\n"
    "Average Waiting Time = (0 + 1 + 5 + 9 + 12) / 5 = 27 / 5 = <b>5.4 ms</b>\n"
    "Average Turnaround Time = (5 + 3 + 8 + 14 + 17) / 5 = 47 / 5 = <b>9.4 ms</b>"
)

pn.section("(iii) Round Robin (q = 1)")
pn.body(
    "Time quantum = 1 ms. Ready queue: processes sorted by arrival. If quantum expires, "
    "current process is appended to queue AFTER any processes arriving at that same instant."
)
pn.info_table(
    [
        "Interval",
        "Running",
        "Ready Queue (after arrival and preemption)",
        "Remaining Bursts",
    ],
    [
        ["0-1", "D", "[B] -- B arrives at 1", "D:4, B:5"],
        [
            "1-2",
            "B",
            "[D] -- D finishes quantum at 2, joins after new arrivals",
            "D:4, B:4, A:3 (A arrives at 2)",
        ],
        [
            "2-3",
            "D",
            "[A, B] -- D quantum ends at 3, joins after E arrives",
            "D:3, B:4, A:3, E:5 (E arrives at 3)",
        ],
        [
            "3-4",
            "A",
            "[B, E, D] -- A quantum ends at 4, joins after C arrives",
            "D:3, B:4, A:2, E:5, C:2 (C arrives at 4)",
        ],
        ["4-5", "B", "[E, D, C, A] -- B quantum ends at 5", "D:3, B:3, A:2, E:5, C:2"],
        ["5-6", "E", "[D, C, A, B] -- E quantum ends at 6", "D:3, B:3, A:2, E:4, C:2"],
        ["6-7", "D", "[C, A, B, E] -- D quantum ends at 7", "D:2, B:3, A:2, E:4, C:2"],
        ["7-8", "C", "[A, B, E, D] -- C quantum ends at 8", "D:2, B:3, A:2, E:4, C:1"],
        ["8-9", "A", "[B, E, D, C] -- A quantum ends at 9", "D:2, B:3, A:1, E:4, C:1"],
        [
            "9-10",
            "B",
            "[E, D, C, A] -- B quantum ends at 10",
            "D:2, B:2, A:1, E:4, C:1",
        ],
        [
            "10-11",
            "E",
            "[D, C, A, B] -- E quantum ends at 11",
            "D:2, B:2, A:1, E:3, C:1",
        ],
        [
            "11-12",
            "D",
            "[C, A, B, E] -- D quantum ends at 12",
            "D:1, B:2, A:1, E:3, C:1",
        ],
        [
            "12-13",
            "C",
            "[A, B, E, D] -- C completes, not added",
            "D:1, B:2, A:1, E:3, C:0 (done)",
        ],
        [
            "13-14",
            "A",
            "[B, E, D] -- A completes, not added",
            "D:1, B:2, A:0 (done), E:3",
        ],
        ["14-15", "B", "[E, D] -- B quantum ends at 15", "D:1, B:1, E:3"],
        ["15-16", "E", "[D, B] -- E quantum ends at 16", "D:1, B:1, E:2"],
        ["16-17", "D", "[B, E] -- D completes, not added", "D:0 (done), B:1, E:2"],
        ["17-18", "B", "[E] -- B completes, not added", "B:0 (done), E:2"],
        ["18-19", "E", "[E] -- E quantum ends at 19", "E:1"],
        ["19-20", "E", "[] -- E completes", "E:0 (done)"],
    ],
)
pn.info_table(
    [
        "Process",
        "Completion Time (CT)",
        "Turnaround Time (TAT = CT - AT)",
        "Waiting Time (WT = TAT - BT)",
    ],
    [
        ["A", "14", "14 - 2 = 12", "12 - 3 = 9"],
        ["B", "18", "18 - 1 = 17", "17 - 5 = 12"],
        ["C", "13", "13 - 4 = 9", "9 - 2 = 7"],
        ["D", "17", "17 - 0 = 17", "17 - 5 = 12"],
        ["E", "20", "20 - 3 = 17", "17 - 5 = 12"],
    ],
)
pn.note(
    "RR (q=1) Gantt Chart: | D | B | D | A | B | E | D | C | A | B | E | D | C | A | B | E | D | B | E | E |\n"
    "Average Waiting Time = (9 + 12 + 7 + 12 + 12) / 5 = 52 / 5 = <b>10.4 ms</b>\n"
    "Average Turnaround Time = (12 + 17 + 9 + 17 + 17) / 5 = 72 / 5 = <b>14.4 ms</b>"
)


pn.section("Problem 2: FCFS & SJF for P1(0,5), P2(2,3), P3(4,1), P4(6,2)")
pn.info_table(
    ["Process", "Arrival Time", "Burst Time"],
    [["P1", "0", "5"], ["P2", "2", "3"], ["P3", "4", "1"], ["P4", "6", "2"]],
)

pn.subsection("FCFS for Problem 2")
pn.info_table(
    ["Process", "Start", "Finish", "TAT", "WT"],
    [
        ["P1", "0", "5", "5", "0"],
        ["P2", "5", "8", "6", "3"],
        ["P3", "8", "9", "5", "4"],
        ["P4", "9", "11", "5", "3"],
    ],
)
pn.note(
    "FCFS: Gantt |P1(0-5)|P2(5-8)|P3(8-9)|P4(9-11)|\n"
    "Avg WT = (0+3+4+3)/4 = 10/4 = <b>2.5 ms</b> | Avg TAT = (5+6+5+5)/4 = 21/4 = <b>5.25 ms</b>"
)

pn.subsection("SJF (Non-Preemptive) for Problem 2")
pn.info_table(
    ["Process", "Start", "Finish", "TAT", "WT"],
    [
        ["P1", "0", "5", "5", "0"],
        ["P3", "5", "6", "2", "1"],
        ["P4", "6", "8", "2", "0"],
        ["P2", "8", "11", "9", "6"],
    ],
)
pn.note(
    "SJF: At t=5: P2(BT=3), P3(BT=1) arrived. P3 shortest → runs. At t=6: P4(BT=2) arrived → runs. At t=8: P2 runs.\n"
    "Gantt |P1(0-5)|P3(5-6)|P4(6-8)|P2(8-11)|\n"
    "Avg WT = (0+1+0+6)/4 = 7/4 = <b>1.75 ms</b> | Avg TAT = (5+2+2+9)/4 = 18/4 = <b>4.5 ms</b>"
)

# -----------------------------------------------------------------------------
#  Q2(e) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q2(e) [10 Marks] -- Semaphore Solution: Bounded Buffer | Semaphore Types\n"
    "(May-June 2024 | Dec 2022 | May-June 2025)"
)

pn.section("Types of Semaphores")
pn.info_table(
    ["Type", "Initial Value", "Purpose", "Example Use"],
    [
        [
            "Binary Semaphore (Mutex)",
            "1",
            "Mutual exclusion — only 1 process in critical section",
            "Protecting shared data structures",
        ],
        [
            "Counting Semaphore",
            "N (resource count)",
            "Managing N instances of a resource",
            "Producer-Consumer buffer with N slots",
        ],
    ],
)

pn.section("Bounded Buffer Problem (Producer-Consumer)")
pn.definition(
    "<b>Bounded Buffer Problem:</b> A classic synchronization problem where a producer process "
    "puts items into a finite buffer and a consumer process removes them. "
    "Three semaphores are needed: "
    "<code>mutex</code> (binary, for mutual exclusion on buffer), "
    "<code>empty</code> (counting, # of empty slots, init=N), "
    "<code>full</code> (counting, # of filled slots, init=0)."
)
pn.code_block(
    """/* Bounded Buffer -- Semaphore Solution */

/* Shared variables */
int buffer[N];           /* circular buffer with N slots */
int in = 0, out = 0;    /* buffer pointers */

semaphore mutex = 1;     /* binary: mutual exclusion */
semaphore empty = N;     /* counting: # empty slots (start = N) */
semaphore full  = 0;     /* counting: # full slots  (start = 0) */

/* PRODUCER process */
do {
    /* produce an item in nextProduced */
    ...produce item...

    wait(empty);         /* block if no empty slot available */
    wait(mutex);         /* enter critical section */

    buffer[in] = nextProduced;
    in = (in + 1) % N;  /* advance circular pointer */

    signal(mutex);       /* leave critical section */
    signal(full);        /* notify consumer: one more full slot */

} while (true);

/* CONSUMER process */
do {
    wait(full);          /* block if no full slot available */
    wait(mutex);         /* enter critical section */

    nextConsumed = buffer[out];
    out = (out + 1) % N; /* advance circular pointer */

    signal(mutex);       /* leave critical section */
    signal(empty);       /* notify producer: one more empty slot */

    /* consume the item in nextConsumed */
    ...consume item...

} while (true);""",
    lang="c",
)
pn.tip(
    "IMPORTANT: Always wait(empty) BEFORE wait(mutex) in producer, and wait(full) BEFORE wait(mutex) "
    "in consumer. Reversing this order causes DEADLOCK."
)

pn.section("Semaphore Solution for Critical Section")
pn.code_block(
    """/* Using binary semaphore (mutex) to solve critical section */
semaphore mutex = 1;

Process Pi:
do {
    wait(mutex);      /* Entry section: request permission */

    /* === CRITICAL SECTION === */
    /* access shared resource here */

    signal(mutex);    /* Exit section: release permission */

    /* === REMAINDER SECTION === */
    /* non-critical code */

} while (true);""",
    lang="c",
)

# #############################################################################
#  QUESTION 3 -- DEADLOCK & MEMORY MANAGEMENT
# #############################################################################
pn.part_box("QUESTION 3 -- DEADLOCK & MEMORY MANAGEMENT")

# -----------------------------------------------------------------------------
#  Q3(a) -- 3 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q3(a) [3 Marks] -- Fragmentation | Deadlock Prevention Methods | Multithreading Models\n"
    "(May-June 2024 | Dec 2022 | May-June 2025)"
)

pn.section("Fragmentation (May-June 2024, Dec 2022)")
pn.info_table(
    ["Type", "Definition", "Cause", "Solution"],
    [
        [
            "Internal Fragmentation",
            "Wasted memory INSIDE an allocated block — the block is larger than the process needs",
            "Fixed-size memory partitions or page sizes larger than actual need",
            "Use smaller page sizes (tradeoff: larger page tables)",
        ],
        [
            "External Fragmentation",
            "Enough total free memory exists but it is NOT contiguous — scattered in small holes",
            "Dynamic memory allocation over time creates holes between allocated blocks",
            "Compaction (move processes), Paging, Segmentation",
        ],
    ],
)
pn.note(
    'Memory needed = "Why is fragmentation needed?" is a misread of the question. '
    "The question asks why fragmentation occurs. Answer: it is an unavoidable side effect of "
    "memory allocation algorithms, not a desired feature."
)

pn.section("Two Methods for Deadlock Prevention (May-June 2025)")
pn.bullet(
    [
        "<b>1. Hold and Wait Prevention:</b> Require a process to request ALL resources it will ever need "
        "at once before starting execution. A process holding some resources cannot request more. "
        "Con: Low resource utilization; a process may wait a long time.",
        "<b>2. Circular Wait Prevention:</b> Impose a total ordering on all resource types. "
        "Each process can only request resources in strictly increasing order of type number. "
        "This breaks the circular chain. Con: Not always convenient to enforce ordering.",
    ]
)

pn.section("Multithreading Models (July-Dec 2024)")
pn.info_table(
    ["Model", "Description", "Pros", "Cons"],
    [
        [
            "Many-to-One",
            "Many user threads → 1 kernel thread. Thread library manages user threads.",
            "Fast thread switching (no kernel involvement)",
            "If one thread makes blocking system call, ALL threads block. No true parallelism.",
        ],
        [
            "One-to-One",
            "Each user thread → 1 kernel thread. Kernel manages each thread.",
            "True parallelism possible. One blocking call doesn't block others.",
            "Creating many user threads = many kernel threads = heavy overhead. Linux/Windows use this.",
        ],
        [
            "Many-to-Many",
            "M user threads → N kernel threads (N ≤ M). OS multiplexes.",
            "True parallelism + no overhead of 1:1. Flexible.",
            "Complex to implement. Requires coordination.",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q3(b) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q3(b) [4 Marks] -- Logical vs Physical Address | Deadlock vs Starvation | Reader-Writers\n"
    "(May-June 2024 | Dec 2022 | May-June 2025 | July-Dec 2024)"
)

pn.section("Logical vs Physical Address")
pn.info_table(
    ["Aspect", "Logical Address", "Physical Address"],
    [
        ["Also Called", "Virtual address", "Real address"],
        [
            "Generated By",
            "CPU during instruction execution",
            "Memory Management Unit (MMU)",
        ],
        ["Seen By", "The running process / programmer", "The actual RAM hardware"],
        [
            "Value",
            "Relative to process base (starts at 0)",
            "Actual location in physical RAM",
        ],
        [
            "Binding",
            "Compile-time or load-time or run-time",
            "Fixed location in physical memory",
        ],
        [
            "Protection",
            "Provides isolation — each process has its own address space",
            "MMU enforces it",
        ],
    ],
)
pn.body(
    "The <b>MMU (Memory Management Unit)</b> translates logical addresses to physical addresses "
    "at runtime using a <b>relocation register</b> (base register): "
    "<code>Physical Address = Logical Address + Relocation Register</code>."
)

pn.section("Deadlock vs Starvation (May-June 2025)")
pn.info_table(
    ["Aspect", "Deadlock", "Starvation"],
    [
        [
            "Definition",
            "Two or more processes are permanently blocked, each waiting for a resource held by another in the set",
            "A process waits indefinitely because other processes keep getting the resource first",
        ],
        [
            "Cause",
            "Circular wait among processes for resources",
            "Poor scheduling (always favoring other processes over this one)",
        ],
        [
            "Resolution",
            "Process termination, resource preemption, or rollback",
            "Aging (gradually increase priority of waiting processes)",
        ],
        [
            "All Processes",
            "ALL involved processes are stuck",
            "Only the starving process is affected; others make progress",
        ],
    ],
)

pn.section("Semaphore Solution for Reader-Writers Problem (July-Dec 2024)")
pn.definition(
    "<b>Reader-Writers Problem:</b> Multiple readers can read a shared database simultaneously "
    "(no conflict), but a writer needs exclusive access. If a writer is writing, no reader or "
    "other writer may access the database."
)
pn.code_block(
    """/* Reader-Writers Problem -- Reader's Preference Solution */

semaphore rw_mutex = 1;  /* mutual exclusion for writers */
semaphore mutex   = 1;   /* protect read_count */
int read_count = 0;       /* # active readers */

/* WRITER */
do {
    wait(rw_mutex);        /* get exclusive access */

    /* ...write to database... */

    signal(rw_mutex);      /* release access */
} while (true);

/* READER */
do {
    wait(mutex);
    read_count++;
    if (read_count == 1)   /* first reader locks writers out */
        wait(rw_mutex);
    signal(mutex);

    /* ...read from database... */

    wait(mutex);
    read_count--;
    if (read_count == 0)   /* last reader allows writers in */
        signal(rw_mutex);
    signal(mutex);
} while (true);""",
    lang="c",
)

# -----------------------------------------------------------------------------
#  Q3(c) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q3(c) [4 Marks] -- Deadlock Necessary Conditions | MMU Role | Critical Section\n"
    "(May-June 2024 | Dec 2022 | May-June 2025)"
)

pn.section("Four Necessary Conditions for Deadlock (Coffman Conditions)")
pn.definition(
    "<b>Deadlock:</b> A state where a set of processes are each waiting for a resource "
    "held by another process in the set — resulting in permanent blocking. "
    "ALL four conditions must hold simultaneously for deadlock to occur."
)
pn.info_table(
    ["Condition", "Definition", "Prevention Approach"],
    [
        [
            "1. Mutual Exclusion",
            "At least one resource must be held in a non-shareable mode — only ONE process can use it at a time.",
            "Make resources shareable (not always possible for printers, tape drives)",
        ],
        [
            "2. Hold and Wait",
            "A process holding at least one resource is waiting to acquire additional resources held by other processes.",
            "Process must request all resources at once before starting OR release all before requesting new ones",
        ],
        [
            "3. No Preemption",
            "Resources cannot be forcibly taken away from a process holding them — they must be voluntarily released.",
            "Allow OS to preempt resources (works for CPU registers/memory, not for printers)",
        ],
        [
            "4. Circular Wait",
            "A circular chain P1→P2→...→Pn→P1 exists where each Pi waits for a resource held by P(i+1).",
            "Impose a total ordering on resource types; require requests in increasing order",
        ],
    ],
)
pn.exam(
    "Exam tip: REMEMBER 'MHNC' — Mutual exclusion, Hold & wait, No preemption, Circular wait. "
    "ALL four must hold for deadlock. Preventing ANY ONE condition prevents deadlock."
)

pn.section("Role of Memory Management Unit (MMU) — May-June 2025")
pn.bullet(
    [
        "<b>Address Translation:</b> Converts logical (virtual) addresses generated by CPU into physical RAM addresses.",
        "<b>Memory Protection:</b> Verifies every memory access is within the process's permitted address range. Raises a segmentation fault if violated.",
        "<b>Paging Support:</b> Maintains the page table and translates page numbers to frame numbers.",
        "<b>TLB Cache:</b> Contains a fast cache (TLB) of recent page-to-frame translations to speed up address translation.",
        "<b>Relocation:</b> Allows processes to be loaded anywhere in physical memory while seeing a uniform virtual address space.",
    ]
)

# -----------------------------------------------------------------------------
#  Q3(d) -- 10 Marks: Banker's Algorithm
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q3(d) [10 Marks] -- Banker's Algorithm | First Fit vs Worst Fit | RAG\n"
    "(May-June 2024 | Dec 2022 | May-June 2025)"
)

pn.section("Banker's Algorithm — Is the System Deadlock Free?")
pn.body(
    "Given: 5 processes (P0–P4), 3 resource types (A, B, C), " "Available = [3, 3, 2]"
)
pn.info_table(
    ["Process", "Allocation A B C", "Max A B C", "Need = Max - Allocation"],
    [
        ["P0", "0 1 0", "7 5 3", "7 4 3"],
        ["P1", "2 0 0", "3 2 2", "1 2 2"],
        ["P2", "3 0 2", "9 0 2", "6 0 0"],
        ["P3", "2 1 1", "2 2 2", "0 1 1"],
        ["P4", "0 0 2", "4 3 3", "4 3 1"],
    ],
)

pn.body("<b>Safety Algorithm — finding a safe sequence:</b>")
pn.info_table(
    [
        "Step",
        "Process Chosen",
        "Available Before",
        "Available After (Add Allocation)",
        "Reason",
    ],
    [
        [
            "1",
            "P1",
            "[3,3,2]",
            "[3+2, 3+0, 2+0] = [5,3,2]",
            "Need[P1]=[1,2,2] ≤ [3,3,2] ✓",
        ],
        [
            "2",
            "P3",
            "[5,3,2]",
            "[5+2, 3+1, 2+1] = [7,4,3]",
            "Need[P3]=[0,1,1] ≤ [5,3,2] ✓",
        ],
        [
            "3",
            "P4",
            "[7,4,3]",
            "[7+0, 4+0, 3+2] = [7,4,5]",
            "Need[P4]=[4,3,1] ≤ [7,4,3] ✓",
        ],
        [
            "4",
            "P0",
            "[7,4,5]",
            "[7+0, 4+1, 5+0] = [7,5,5]",
            "Need[P0]=[7,4,3] ≤ [7,4,5] ✓",
        ],
        [
            "5",
            "P2",
            "[7,5,5]",
            "[7+3, 5+0, 5+2] = [10,5,7]",
            "Need[P2]=[6,0,0] ≤ [7,5,5] ✓",
        ],
    ],
)
pn.note(
    "Safe Sequence: <b>P1 → P3 → P4 → P0 → P2</b>\n"
    "Since a safe sequence exists, the system is in a SAFE STATE and is DEADLOCK FREE."
)

pn.section("First Fit vs Worst Fit Memory Allocation")
pn.body(
    "Memory blocks (KB): 100, 500, 200, 300, 600 | "
    "Processes (KB): 212, 417, 112, 426"
)

pn.subsection("First Fit")
pn.body("Allocate to the FIRST block big enough to fit the process.")
pn.info_table(
    ["Process (KB)", "Allocated to Block", "Block Size", "Remaining"],
    [
        ["212", "500 KB block", "500 KB", "288 KB left"],
        ["417", "600 KB block", "600 KB", "183 KB left"],
        ["112", "288 KB remaining (500 block)", "288 KB", "176 KB left"],
        ["426", "No block large enough", "—", "Not allocated"],
    ],
)
pn.note(
    "First Fit: 212→500, 417→600, 112→leftover of 500. Process 426 cannot be allocated."
)

pn.subsection("Worst Fit")
pn.body("Allocate to the LARGEST available block.")
pn.info_table(
    ["Process (KB)", "Allocated to Block", "Block Size", "Remaining"],
    [
        ["212", "600 KB block (largest)", "600 KB", "388 KB left"],
        ["417", "500 KB block (now largest)", "500 KB", "83 KB left"],
        ["112", "388 KB remaining (600 block)", "388 KB", "276 KB left"],
        ["426", "No block large enough (276, 83, 300 all < 426)", "—", "Not allocated"],
    ],
)
pn.note(
    "Worst Fit: 212→600, 417→500, 112→leftover. Process 426 cannot be allocated in either strategy."
)

pn.section("Resource Allocation Graph (RAG) — May-June 2025")
pn.definition(
    "<b>RAG:</b> A directed graph used to describe deadlock states. "
    "Vertices: Processes (circles P) and Resources (squares R). "
    "Edges: Request edge P→R (process requesting resource) and "
    "Assignment edge R→P (resource assigned to process). "
    "<b>Deadlock detection:</b> If RAG contains a cycle AND each resource has only 1 instance → deadlock. "
    "If multiple instances → cycle is necessary but not sufficient for deadlock."
)
pn.info_table(
    ["Graph Property", "Single Instance Resources", "Multiple Instance Resources"],
    [
        ["Cycle exists", "DEADLOCK guaranteed", "Deadlock POSSIBLE but not certain"],
        ["No cycle", "No deadlock", "No deadlock"],
    ],
)

pn.subsection("1. RAG with a Deadlock (Single-Instance Resource Cycle)")
pn.body(
    "A cycle exists: P1 → R2 → P2 → R3 → P3 → R1 → P1. "
    "Since resources R1, R2, and R3 have only one instance each, "
    "this cycle represents a permanent deadlock state where none of these processes can progress."
)

net_rag_dl = pd.NetworkDiagram(
    width=pn.CW,
    height=350,
    theme=diag_theme,
    caption="Fig 3.2: Resource Allocation Graph with Deadlock (Cycle & Single-Instance)",
)
net_rag_dl.node("p1", "Process P1", x=245, y=280, kind="server")
net_rag_dl.node("r2", "Resource R2\n[1 instance]", x=380, y=200, kind="database", label_pos="right")
net_rag_dl.node("p2", "Process P2", x=380, y=100, kind="server")
net_rag_dl.node("r3", "Resource R3\n[1 instance]", x=245, y=40, kind="database")
net_rag_dl.node("p3", "Process P3", x=110, y=100, kind="server")
net_rag_dl.node("r1", "Resource R1\n[1 instance]", x=110, y=200, kind="database", label_pos="left")

net_rag_dl.link("r1", "p1", label="assigned")
net_rag_dl.link("p1", "r2", label="requests")
net_rag_dl.link("r2", "p2", label="assigned")
net_rag_dl.link("p2", "r3", label="requests")
net_rag_dl.link("r3", "p3", label="assigned")
net_rag_dl.link("p3", "r1", label="requests")
pn.story.extend(net_rag_dl.as_flowable())

pn.subsection("2. RAG with a Cycle but NO Deadlock (Multi-Instance)")
pn.body(
    "A cycle exists: P1 → R1 → P2 → R2 → P1. "
    "However, both R1 and R2 have 2 instances. Process P3 holds an instance of R1, and P4 holds an instance of R2. "
    "Because P3 and P4 do not request resources, they can complete and release their allocations, "
    "breaking the cycle. Hence, there is NO deadlock."
)

net_rag_nodl = pd.NetworkDiagram(
    width=pn.CW,
    height=250,
    theme=diag_theme,
    caption="Fig 3.3: Resource Allocation Graph with a Cycle but NO Deadlock",
)
net_rag_nodl.node("p1", "Process P1", x=185, y=200, kind="server")
net_rag_nodl.node("p2", "Process P2", x=305, y=200, kind="server")
net_rag_nodl.node("r1", "Resource R1\n[2 instances]", x=185, y=80, kind="database")
net_rag_nodl.node("r2", "Resource R2\n[2 instances]", x=305, y=80, kind="database")
net_rag_nodl.node("p3", "Process P3", x=105, y=80, kind="server")
net_rag_nodl.node("p4", "Process P4", x=385, y=80, kind="server")

net_rag_nodl.link("p1", "r1", label="requests")
net_rag_nodl.link("r1", "p2", label="assigned")
net_rag_nodl.link("r1", "p3", label="assigned")
net_rag_nodl.link("p2", "r2", label="requests")
net_rag_nodl.link("r2", "p1", label="assigned")
net_rag_nodl.link("r2", "p4", label="assigned")
pn.story.extend(net_rag_nodl.as_flowable())
pn.br()

# -----------------------------------------------------------------------------
#  Q3(e) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q3(e) [10 Marks] -- Deadlock Recovery & Prevention | Peterson's Solution\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024)"
)

pn.section("Deadlock Prevention Schemes")
pn.body(
    "Prevent deadlock by ensuring at least ONE of the four Coffman conditions cannot hold:"
)
pn.info_table(
    ["Condition to Break", "Method", "How it Works"],
    [
        [
            "Mutual Exclusion",
            "Use shareable resources where possible",
            "Read-only files can be shared. But printers/tape drives cannot — not always possible.",
        ],
        [
            "Hold and Wait",
            "Request all resources at once (pre-allocation)",
            "Process declares max resource needs upfront and gets all before starting. Or release before requesting new.",
        ],
        [
            "No Preemption",
            "Preempt resources from blocked processes",
            "If a process holding resources requests another that's unavailable, preempt its held resources. Works for CPU, memory pages.",
        ],
        [
            "Circular Wait",
            "Impose total ordering on resource types",
            "Number all resource types. Processes must request in strictly increasing order. No cycle possible.",
        ],
    ],
)

pn.section("Deadlock Recovery Schemes")
pn.info_table(
    ["Recovery Method", "Approach", "Cost"],
    [
        [
            "Process Termination",
            "Abort all deadlocked processes (drastic) OR abort one at a time until cycle broken (selective).",
            "High — work done by aborted processes is lost. Choose victim by priority, CPU time, resources held.",
        ],
        [
            "Resource Preemption",
            "Forcibly take resources from some processes and give to others to break the cycle.",
            "Must handle rollback (return victim to a safe state), starvation prevention (cannot always pick same victim).",
        ],
        [
            "Checkpoint & Rollback",
            "Periodically save process state. On deadlock, roll back to checkpoint before deadlock began.",
            "Storage overhead for checkpoints. Process loses work since last checkpoint.",
        ],
    ],
)

pn.section("Peterson's Solution for Critical Section")
pn.definition(
    "<b>Peterson's Solution:</b> A classical software-only solution to the critical section "
    "problem for TWO processes. It satisfies all three requirements: mutual exclusion, "
    "progress, and bounded waiting. Uses two shared variables: "
    "<code>turn</code> (whose turn to enter CS) and <code>flag[2]</code> (intent to enter CS)."
)
pn.code_block(
    """/* Peterson's Solution for TWO processes (i and j, where j = 1-i) */

int turn;       /* whose turn: 0 or 1 */
bool flag[2];   /* flag[i]=true means Pi wants to enter CS */

/* Process Pi's code: */
do {
    flag[i] = true;     /* Signal intent to enter CS */
    turn = j;           /* Give priority to the other process */

    /* BUSY WAIT: enter only when other doesn't want to enter OR it's our turn */
    while (flag[j] && turn == j)
        ;               /* wait */

    /* === CRITICAL SECTION === */

    flag[i] = false;    /* Done -- no longer interested */

    /* === REMAINDER SECTION === */

} while (true);

/* Why it works:
   - Mutual Exclusion: Both cannot pass while(flag[j] && turn==j) simultaneously
   - Progress: If Pj doesn't want CS (flag[j]=false), Pi enters immediately
   - Bounded Waiting: Pi waits at most ONE turn of Pj */""",
    lang="c",
)

# #############################################################################
#  QUESTION 4 -- VIRTUAL MEMORY & PAGING
# #############################################################################
pn.part_box("QUESTION 4 -- VIRTUAL MEMORY & PAGING")

# -----------------------------------------------------------------------------
#  Q4(a) -- 3 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q4(a) [3 Marks] -- TLB | Page Table | Page Fault\n"
    "(May-June 2024 | Dec 2022 | May-June 2025 | July-Dec 2024)"
)

pn.section("Why TLB is Used (May-June 2024 | Dec 2022)")
pn.definition(
    "<b>TLB (Translation Lookaside Buffer):</b> A small, fast, associative cache in the MMU "
    "that stores recent page-to-frame translations. Without TLB, every memory access requires "
    "TWO memory accesses (one for page table, one for actual data) — halving effective memory speed. "
    "TLB reduces this to 1 access on a hit."
)
pn.info_table(
    ["Scenario", "Memory Accesses Required", "Effective Access Time (EAT)"],
    [
        ["No TLB", "2 (page table + data)", "2 × memory access time"],
        [
            "TLB Hit (h=hit ratio)",
            "1 (data only)",
            "h × (1 + memory_time) + (1-h) × (2 + memory_time)",
        ],
    ],
)
pn.bullet(
    [
        "<b>TLB Hit:</b> Page number found in TLB → frame number immediately available → 1 memory access.",
        "<b>TLB Miss:</b> Not in TLB → access page table in memory → load entry into TLB → 2 memory accesses.",
        "<b>ASID:</b> TLB entries can contain Address Space Identifiers to avoid flushing on context switch.",
    ]
)

pn.section("Page Table (May-June 2025)")
pn.definition(
    "<b>Page Table:</b> A per-process data structure maintained by the OS that maps "
    "logical page numbers to physical frame numbers. Each entry (PTE) contains: "
    "frame number, valid/invalid bit, dirty bit (modified), referenced bit, protection bits."
)

pn.section("Page Fault (May-June 2025)")
pn.definition(
    "<b>Page Fault:</b> Occurs when a process accesses a page that is NOT currently in main memory "
    "(valid bit = 0 in the PTE). The OS page fault handler must: "
    "(1) Find the page on disk. "
    "(2) Find a free frame (or evict a victim frame using a replacement algorithm). "
    "(3) Load the page into the frame. "
    "(4) Update the page table entry. "
    "(5) Restart the faulting instruction."
)

# -----------------------------------------------------------------------------
#  Q4(b) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q4(b) [4 Marks] -- Thrashing | Segmentation | Address Binding\n"
    "(May-June 2024 | Dec 2022 | July-Dec 2024 | May-June 2025)"
)

pn.section("Thrashing")
pn.definition(
    "<b>Thrashing:</b> A condition where a process spends more time paging (swapping pages in "
    "and out) than executing. The CPU utilization drops dramatically. "
    "The OS sees low CPU utilization and adds more processes (to increase utilization), "
    "making thrashing worse — a vicious cycle."
)
pn.bullet(
    [
        "<b>Cause 1 — Insufficient Frames:</b> A process does not have enough frames for its working set. Every few instructions cause a page fault.",
        "<b>Cause 2 — High Degree of Multiprogramming:</b> Too many processes share too little memory — each steals frames from others.",
        "<b>Cause 3 — Poor Locality:</b> Programs that access data in a random, non-local pattern cause frequent page faults.",
        "<b>Solution — Working Set Model:</b> Track the set of pages a process has used in the last Δ references (working set window). Allocate enough frames for the working set.",
        "<b>Solution — Page-Fault Frequency (PFF):</b> Monitor page fault rate. Too high → give more frames. Too low → take frames back.",
    ]
)

pn.section("Segmentation (May-June 2025)")
pn.definition(
    "<b>Segmentation:</b> A memory management scheme where a program's address space is divided "
    "into logical segments corresponding to the program's natural structure (code, data, stack, heap, etc.). "
    "Each segment has a base address and a limit (length). "
    "Logical address = (segment number, offset). "
    "Physical address = segment_table[segment_number].base + offset."
)

# -----------------------------------------------------------------------------
#  Q4(c) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q4(c) [4 Marks] -- Demand Paging | Address Binding | Page Size Impact\n"
    "(May-June 2024 | July-Dec 2024)"
)

pn.section("Demand Paging")
pn.definition(
    "<b>Demand Paging:</b> A lazy loading strategy where pages are loaded into memory ONLY when "
    "they are accessed (demanded), NOT when the process starts. "
    "This reduces startup time and memory usage since only needed pages occupy frames."
)
pn.bullet(
    [
        "When a process starts, only a minimal set of pages (or none) are loaded.",
        "When a page is accessed and not in memory, a <b>page fault</b> occurs.",
        "OS handles the fault by loading the required page from disk into a free frame.",
        "Execution resumes. Subsequent accesses to the same page are fast (no fault).",
        "<b>Advantage:</b> Supports virtual memory larger than physical RAM. Fast process startup.",
    ]
)

pn.section("Address Binding")
pn.info_table(
    ["Binding Time", "When It Occurs", "Meaning", "Example"],
    [
        [
            "Compile-Time",
            "At compilation",
            "Absolute addresses embedded in code. Process must load at same address every time.",
            "Old .COM files in MS-DOS",
        ],
        [
            "Load-Time",
            "When OS loads program into memory",
            "Relocatable code: linker generates relocatable addresses, loader fixes them up.",
            "Early Unix linker/loader",
        ],
        [
            "Run-Time (Dynamic)",
            "During execution, by MMU hardware",
            "Logical addresses translated to physical addresses every time by MMU. Process can be moved in memory.",
            "Modern OS: Windows, Linux with virtual memory",
        ],
    ],
)

pn.section("Impact of Page Size on System Performance")
pn.info_table(
    ["Effect", "Small Page Size", "Large Page Size"],
    [
        [
            "Internal Fragmentation",
            "Less waste in last page (good)",
            "More waste in last page (bad)",
        ],
        [
            "Page Table Size",
            "More entries needed — larger table (bad)",
            "Fewer entries — smaller table (good)",
        ],
        [
            "Page Fault Rate",
            "More faults — less data per page load (bad)",
            "Fewer faults — more data per load (good)",
        ],
        [
            "Disk I/O",
            "Small transfers — inefficient I/O (bad)",
            "Large transfers — efficient I/O (good)",
        ],
        [
            "TLB Coverage",
            "Less memory covered per TLB entry (bad)",
            "More memory covered per TLB entry (good)",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q4(d) -- 10 Marks: Page Replacement Numericals
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q4(d) [10 Marks] -- Page Replacement Algorithms: FIFO, LRU, Optimal\n"
    "(May-June 2024 | Dec 2022 | May-June 2025 | July-Dec 2024)"
)

pn.section("Reference String 1: 1,2,3,4,2,1,5,6,2,1,2,3,7,6,3,2,1,2,3,6  |  3 Frames")
pn.info_table(
    ["Algorithm", "Total Page Faults", "Hit Count"],
    [
        ["FIFO (First-In-First-Out)", "16", "4"],
        ["LRU (Least Recently Used)", "15", "5"],
        ["Optimal (Bélády's)", "11", "9"],
    ],
)

pn.subsection("FIFO Trace (3 frames)")
pn.body(
    "FIFO replaces the page that has been in memory the LONGEST (first in = first out)."
)
pn.info_table(
    ["Ref", "Frames (oldest→newest)", "Fault?"],
    [
        ["1", "[1, -, -]", "YES (F)"],
        ["2", "[1, 2, -]", "YES (F)"],
        ["3", "[1, 2, 3]", "YES (F)"],
        ["4", "[4, 2, 3]  replace 1", "YES (F)"],
        ["2", "[4, 2, 3]", "NO (hit)"],
        ["1", "[4, 1, 3]  replace 2", "YES (F)"],
        ["5", "[4, 1, 5]  replace 3", "YES (F)"],
        ["6", "[6, 1, 5]  replace 4", "YES (F)"],
        ["2", "[6, 2, 5]  replace 1", "YES (F)"],
        ["1", "[6, 2, 1]  replace 5", "YES (F)"],
        ["2", "[6, 2, 1]", "NO (hit)"],
        ["3", "[3, 2, 1]  replace 6", "YES (F)"],
        ["7", "[3, 7, 1]  replace 2", "YES (F)"],
        ["6", "[3, 7, 6]  replace 1", "YES (F)"],
        ["3", "[3, 7, 6]", "NO (hit)"],
        ["2", "[2, 7, 6]  replace 3", "YES (F)"],
        ["1", "[2, 1, 6]  replace 7", "YES (F)"],
        ["2", "[2, 1, 6]", "NO (hit)"],
        ["3", "[2, 1, 3]  replace 6", "YES (F)"],
        ["6", "[6, 1, 3]  replace 2", "YES (F)"],
    ],
)
pn.note("FIFO Total Faults = <b>16</b>")

pn.subsection("LRU Trace (3 frames)")
pn.body(
    "LRU replaces the page that was LEAST RECENTLY USED (not referenced for the longest time)."
)
pn.info_table(
    ["Ref", "Frames", "Fault?"],
    [
        ["1", "[1, -, -]", "YES"],
        ["2", "[1, 2, -]", "YES"],
        ["3", "[1, 2, 3]", "YES"],
        ["4", "[4, 2, 3]  LRU=1", "YES"],
        ["2", "[4, 2, 3]", "NO"],
        ["1", "[4, 2, 1]  LRU=3", "YES"],
        ["5", "[5, 2, 1]  LRU=4", "YES"],
        ["6", "[5, 6, 1]  LRU=2", "YES"],
        ["2", "[5, 6, 2]  LRU=1", "YES"],
        ["1", "[1, 6, 2]  LRU=5", "YES"],
        ["2", "[1, 6, 2]", "NO"],
        ["3", "[1, 3, 2]  LRU=6", "YES"],
        ["7", "[7, 3, 2]  LRU=1", "YES"],
        ["6", "[7, 3, 6]  LRU=2", "YES"],
        ["3", "[7, 3, 6]", "NO"],
        ["2", "[2, 3, 6]  LRU=7", "YES"],
        ["1", "[2, 1, 6]  LRU=3", "YES"],
        ["2", "[2, 1, 6]", "NO"],
        ["3", "[2, 1, 3]  LRU=6", "YES"],
        ["6", "[6, 1, 3]  LRU=2", "YES"],
    ],
)
pn.note("LRU Total Faults = <b>15</b>")

pn.subsection("Optimal Replacement Result")
pn.body(
    "Optimal (Bélády's) replaces the page that will NOT be used for the LONGEST time in the future. "
    "This is theoretical (requires future knowledge) but gives a lower bound comparison."
)
pn.note(
    "Optimal Total Faults = <b>11</b>  |  Comparison: Optimal (11) &lt; LRU (15) &lt; FIFO (16)"
)

pn.section("Reference String 2: 7,0,1,2,0,3,0,4,2,3,0,3,2  |  3 Frames")
pn.subsection("FIFO")
pn.info_table(
    ["Ref", "Frames", "Fault?"],
    [
        ["7", "[7,-,-]", "YES"],
        ["0", "[7,0,-]", "YES"],
        ["1", "[7,0,1]", "YES"],
        ["2", "[2,0,1] repl 7", "YES"],
        ["0", "[2,0,1]", "NO"],
        ["3", "[2,3,1] repl 0", "YES"],
        ["0", "[2,3,0] repl 1", "YES"],
        ["4", "[4,3,0] repl 2", "YES"],
        ["2", "[4,2,0] repl 3", "YES"],
        ["3", "[4,2,3] repl 0", "YES"],
        ["0", "[0,2,3] repl 4", "YES"],
        ["3", "[0,2,3]", "NO"],
        ["2", "[0,2,3]", "NO"],
    ],
)
pn.note("FIFO Faults = <b>10</b> (3 hits)")

pn.subsection("LRU")
pn.info_table(
    ["Ref", "Frames", "Fault?"],
    [
        ["7", "[7,-,-]", "YES"],
        ["0", "[7,0,-]", "YES"],
        ["1", "[7,0,1]", "YES"],
        ["2", "[2,0,1] LRU=7", "YES"],
        ["0", "[2,0,1]", "NO"],
        ["3", "[2,0,3] LRU=1", "YES"],
        ["0", "[2,0,3]", "NO"],
        ["4", "[4,0,3] LRU=2", "YES"],
        ["2", "[4,0,2] LRU=3", "YES"],
        ["3", "[4,3,2] LRU=0", "YES"],
        ["0", "[0,3,2] LRU=4", "YES"],
        ["3", "[0,3,2]", "NO"],
        ["2", "[0,3,2]", "NO"],
    ],
)
pn.note("LRU Faults = <b>9</b> (4 hits)  |  Comparison: LRU (9) &lt; FIFO (10)")

# -----------------------------------------------------------------------------
#  Q4(e) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q4(e) [10 Marks] -- Segmentation Details | Thrashing: Working Set & PFF | Paging\n"
    "(May-June 2025 | July-Dec 2024)"
)

pn.section("Paging in Detail (July-Dec 2024)")
pn.definition(
    "<b>Paging:</b> A memory management scheme that avoids external fragmentation by dividing "
    "both physical memory and logical address space into fixed-size blocks. "
    "Physical memory blocks = <b>frames</b>. Logical address blocks = <b>pages</b>. "
    "Page size = Frame size (typically 4 KB on modern systems)."
)
pn.bullet(
    [
        "<b>Page Table:</b> OS maintains a page table per process mapping page number → frame number.",
        "<b>Logical Address:</b> Divided into page number (p) and page offset (d).",
        "<b>Physical Address:</b> frame number f combined with offset d → actual RAM location.",
        "<b>No External Fragmentation:</b> Any free frame can hold any page — no contiguous requirement.",
        "<b>Internal Fragmentation:</b> The last page of a process may not fill an entire frame.",
        "<b>Advantages:</b> Simple allocation, no external fragmentation, easy protection.",
        "<b>Disadvantages:</b> Page table overhead (for large address spaces), internal fragmentation.",
    ]
)

pn.section("Segmentation with Address Translation Diagram")
pn.definition(
    "<b>Segmentation:</b> Logical address = (segment number s, offset d). "
    "The OS maintains a <b>segment table</b> per process. Each entry has: base (start physical address) and limit (length). "
    "Physical address = segment_table[s].base + d, after verifying d &lt; segment_table[s].limit."
)
pn.code_block(
    """/* Virtual to Physical address translation in Segmented System */

Logical address  = (segment_number s, offset d)

/* MMU does: */
if d >= segment_table[s].limit:
    raise SEGMENTATION_FAULT   /* protection violation */

physical_address = segment_table[s].base + d""",
    lang="c",
)

fc_seg = pd.Flowchart(
    width=pn.CW,
    height=250,
    theme=diag_theme,
    caption="Fig 4.1: Segmentation Address Translation Scheme with Protection Check",
)
fc_seg.terminal("cpu", "CPU generates\nlogical address (s, d)")
fc_seg.process("lookup", "Lookup Segment s\nin Segment Table\n(gets base, limit)")
fc_seg.decision("check", "Is offset d\n< limit?")
fc_seg.terminal("trap", "Trap: Segment Fault\n(Error)")
fc_seg.process("calc", "Calculate Address:\nPhysical = base + d")
fc_seg.terminal("ram", "Access Physical RAM")

fc_seg.edge("cpu", "lookup")
fc_seg.edge("lookup", "check")
fc_seg.edge("check", "calc", branch="yes")
fc_seg.edge("check", "trap", branch="no")
fc_seg.edge("calc", "ram")
pn.story.extend(fc_seg.as_flowable())
pn.br()

pn.section("Handling Thrashing: Working Set Model & Page-Fault Frequency")
pn.info_table(
    ["Method", "Approach", "How It Prevents Thrashing"],
    [
        [
            "Working Set Model",
            "Track the set of pages referenced in the last Δ references (working set window W). "
            "Allocate at least |W| frames to a process.",
            "Ensures a process has enough frames for its current locality. If sum of all working sets > total frames → reduce multiprogramming by swapping out a process.",
        ],
        [
            "Page-Fault Frequency (PFF)",
            "Monitor each process's page fault rate. Set upper (too high) and lower (too low) bounds.",
            "If rate > upper bound → give more frames. If rate < lower bound → take frames back. If rate too high and no free frames → swap out a process.",
        ],
    ],
)

# #############################################################################
#  QUESTION 5 -- FILE & DISK MANAGEMENT
# #############################################################################
pn.part_box("QUESTION 5 -- FILE SYSTEMS & DISK MANAGEMENT")

# -----------------------------------------------------------------------------
#  Q5(a) -- 3 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q5(a) [3 Marks] -- File Attributes & Operations | File Descriptor | Belady's Anomaly\n"
    "(May-June 2024 | Dec 2022 | May-June 2025 | July-Dec 2024)"
)

pn.section("File Attributes (May-June 2024 | May-June 2025)")
pn.info_table(
    ["Attribute", "Description"],
    [
        ["Name", "Symbolic name — the only information kept in human-readable form"],
        [
            "Identifier",
            "Unique numeric tag (inode number on Unix) identifying the file within the file system",
        ],
        ["Type", "File type information (executable, text, binary, directory, link)"],
        [
            "Location",
            "Pointer to the device and exact location of file data on that device",
        ],
        ["Size", "Current size in bytes, words, or blocks"],
        ["Protection", "Access control information — who can read, write, execute"],
        ["Timestamps", "Date/time of creation, last modification, last access"],
        ["Owner", "User ID of the file's creator/owner"],
    ],
)

pn.section("File Operations")
pn.bullet(
    [
        "<b>Create:</b> Allocate space in file system, create directory entry with file name and location.",
        "<b>Write:</b> System call with file descriptor and data to write. Kernel updates write pointer.",
        "<b>Read:</b> System call with file descriptor and buffer. Kernel updates read pointer.",
        "<b>Seek (Reposition):</b> Move file pointer to a given position for random access.",
        "<b>Delete:</b> Remove directory entry; release allocated file space to free space list.",
        "<b>Truncate:</b> Erase file contents but keep file attributes (reset length to 0).",
        "<b>Open:</b> Search directory, copy file attributes and disk addresses to open-file table; return file descriptor.",
        "<b>Close:</b> Remove entry from open-file table; flush any modified blocks to disk.",
    ]
)

pn.section("Structure of a File (July-Dec 2024)")
pn.definition(
    "<b>File Structure:</b> The internal organization of a file, which determines how "
    "its data is stored and accessed. Operating systems support different levels of file structure:"
)
pn.info_table(
    ["File Structure Type", "Description", "Used In"],
    [
        [
            "1. Unstructured Byte Sequence",
            "The file is a sequence of unstructured bytes. The OS does not know or care about the contents. Maximum flexibility for applications.",
            "Modern OS: Linux, Windows, macOS, UNIX",
        ],
        [
            "2. Record Sequence",
            "The file is a sequence of fixed-length or variable-length records. Read/write operations happen at the record level.",
            "Mainframe OS (MVS), database files",
        ],
        [
            "3. Tree-Structured / Indexed",
            "The file contains a tree of records of varying lengths, with key fields allowing fast indexed searches.",
            "Legacy systems, database indexes",
        ],
    ],
)

pn.section("File Descriptor (May-June 2025)")
pn.definition(
    "<b>File Descriptor:</b> A small non-negative integer returned by the <code>open()</code> "
    "system call that uniquely identifies an open file within a process. "
    "All subsequent file operations (read, write, seek, close) use this integer. "
    "Standard file descriptors: 0 = stdin, 1 = stdout, 2 = stderr."
)

pn.section("Belady's Anomaly (July-Dec 2024)")
pn.definition(
    "<b>Belady's Anomaly:</b> The counter-intuitive phenomenon in FIFO page replacement where "
    "<b>increasing the number of frames can increase the number of page faults</b>. "
    "This happens because FIFO doesn't consider recency of use — adding more frames changes "
    "which page gets evicted and may cause previously-safe pages to be evicted at worse times. "
    "LRU and Optimal replacement algorithms do NOT suffer from Belady's anomaly."
)

# -----------------------------------------------------------------------------
#  Q5(b) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q5(b) [4 Marks] -- File Allocation Methods | FAT | Directory Types\n"
    "(May-June 2024 | May-June 2025 | July-Dec 2024)"
)

pn.section("File Allocation Methods")
pn.info_table(
    ["Method", "How It Works", "Advantages", "Disadvantages"],
    [
        [
            "Contiguous Allocation",
            "Each file occupies a set of contiguous blocks on disk. Directory stores starting block and length.",
            "Simple. Fast sequential access. Fast direct access (block i = start + i).",
            "External fragmentation. File cannot grow easily. Requires knowing file size upfront.",
        ],
        [
            "Linked Allocation",
            "Each file is a linked list of disk blocks. Each block contains a pointer to the next. Directory stores first and last block.",
            "No external fragmentation. Files can grow easily. Any free block can be used.",
            "No direct access (must traverse chain). Pointer overhead per block. Reliability issue if pointer corrupted.",
        ],
        [
            "Indexed Allocation",
            "One special index block holds all pointers to file's data blocks. Directory stores pointer to index block.",
            "Supports direct access. No external fragmentation. No pointer overhead per data block.",
            "Index block overhead. Single index block limits file size (use multi-level indexing for large files).",
        ],
    ],
)

pn.section("File Allocation Table (FAT) — May-June 2025")
pn.definition(
    "<b>FAT:</b> A disk-based table kept at the beginning of the volume. "
    "Each entry corresponds to one cluster (group of disk blocks). "
    "Entry contains: the next cluster in the file's chain, or EOF marker, or 0 (free). "
    "FAT is essentially a linked allocation where the linked list is stored in a dedicated table "
    "rather than in each block — enabling faster traversal and direct access by scanning the table."
)

# -----------------------------------------------------------------------------
#  Q5(c) -- 4 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q5(c) [4 Marks] -- Directory Types | Tree-Structured Directory\n"
    "(May-June 2024 | May-June 2025 | July-Dec 2024)"
)

pn.section("Types of Directory Structures")
pn.info_table(
    ["Structure", "Description", "Advantages", "Disadvantages"],
    [
        [
            "Single-Level Directory",
            "All files in ONE directory shared by all users.",
            "Simple, easy to implement.",
            "No grouping. Name collisions between users. Poor for large systems.",
        ],
        [
            "Two-Level Directory",
            "Separate directory per user (UFD — User File Directory) under a Master File Directory (MFD).",
            "Resolves naming collisions between users. Efficient search per user.",
            "Users cannot share files easily. No grouping within a user's files.",
        ],
        [
            "Tree-Structured Directory",
            "Hierarchical tree of directories. Arbitrary depth. Each directory can contain files and subdirectories.",
            "Efficient searching. Grouping of related files. Current working directory concept.",
            "Complex to implement. Deleting a directory may cascade. Path names can be long.",
        ],
        [
            "Acyclic-Graph Directory",
            "Allows shared subdirectories and files using hard links or symbolic links.",
            "Files/dirs can be shared without duplication. Flexible access paths.",
            "Dangling pointers when shared file deleted. Deletion is complex (reference counting needed).",
        ],
        [
            "General Graph Directory",
            "Allows cycles in directory graph via symbolic links.",
            "Maximum flexibility.",
            "Traversal may loop. Requires garbage collection. Not commonly used.",
        ],
    ],
)

pn.section("Tree-Structured Directory Detail — May-June 2025")
pn.definition(
    "<b>Tree-Structured Directory:</b> The most common structure used in modern operating systems "
    "(Linux ext4, Windows NTFS, macOS HFS+). The root directory <code>/</code> is the top. "
    "Every file/directory has a unique absolute path from root. "
    "Users can create their own subdirectories for grouping. "
    "The concept of <b>current working directory</b> (CWD) allows relative paths."
)

# -----------------------------------------------------------------------------
#  Q5(d) -- 10/20 Marks: Disk Scheduling & File Access Methods
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q5(d) [10 Marks] -- Disk Scheduling (FCFS/C-SCAN/SSTF) | File Access Methods\n"
    "(May-June 2024 | May-June 2025 | July-Dec 2024)"
)

pn.section("File Access Methods (July-Dec 2024)")
pn.definition(
    "<b>File Access Methods:</b> Determine the order and mechanism by which a process reads or writes file data."
)
pn.info_table(
    ["Access Method", "Operation Principle", "Common Operations", "Example Use Case"],
    [
        [
            "Sequential Access",
            "Information is processed in order, one byte/record after another. Cannot skip ahead without reading intermediate blocks.",
            "read_next(), write_next(), reset(), rewind()",
            "Text files, source code compilation, audio/video streaming files",
        ],
        [
            "Direct (Random) Access",
            "File is viewed as a numbered sequence of blocks/records. Can read or write any block directly in any order.",
            "read(block_n), write(block_n), seek(pos)",
            "Databases (fast row lookup), virtual disks, key-value stores",
        ],
        [
            "Indexed Access",
            "An index containing pointers to blocks is searched first (often via binary search or B-tree). The pointer is then used to perform direct access.",
            "search_index(key), read_record()",
            "Database index tables, filesystem metadata searches",
        ],
    ],
)

pn.section("Problem Setup")
pn.body(
    "Disk head currently at track <b>143</b>. Previous position: track 125 (moving toward higher tracks). "
    "Total tracks: 0–199. "
    "Request queue (FIFO order): 86, 147, 91, 177, 94, 150"
)

pn.section("(i) FCFS — First Come First Served")
pn.body("Service requests in the order they arrive in the queue.")
pn.info_table(
    ["Step", "From Track", "To Track", "Head Movement (|To - From|)"],
    [
        ["Start", "—", "143", "—"],
        ["1", "143", "86", "57"],
        ["2", "86", "147", "61"],
        ["3", "147", "91", "56"],
        ["4", "91", "177", "86"],
        ["5", "177", "94", "83"],
        ["6", "94", "150", "56"],
    ],
)
pn.note("FCFS Total Head Movement = 57 + 61 + 56 + 86 + 83 + 56 = <b>399 tracks</b>")

pn.section("(ii) SSTF — Shortest Seek Time First")
pn.body("Always service the closest request to current head position.")
pn.info_table(
    ["Step", "Current", "Pending Requests", "Chosen (Nearest)", "Movement"],
    [
        ["1", "143", "86,147,91,177,94,150", "147 (dist=4)", "4"],
        ["2", "147", "86,91,177,94,150", "150 (dist=3)", "3"],
        ["3", "150", "86,91,177,94", "177 (dist=27)", "27"],
        ["4", "177", "86,91,94", "94 (dist=83)", "83"],
        ["5", "94", "86,91", "91 (dist=3)", "3"],
        ["6", "91", "86", "86 (dist=5)", "5"],
    ],
)
pn.note("SSTF Total Head Movement = 4 + 3 + 27 + 83 + 3 + 5 = <b>125 tracks</b>")

pn.section("(iii) C-SCAN — Circular SCAN")
pn.body(
    "Head moves toward higher tracks, servicing requests. On reaching the end (199), "
    "it jumps to track 0 (without servicing) and sweeps again toward higher tracks. "
    "Current direction: toward higher tracks (from 143, prev was 125)."
)
pn.info_table(
    ["Step", "Track Serviced / Action", "Movement"],
    [
        ["1", "Service 147", "4"],
        ["2", "Service 150", "3"],
        ["3", "Service 177", "27"],
        ["4", "Go to end (199)", "22"],
        ["5", "Jump to 0 (no service)", "199"],
        ["6", "Service 86", "86"],
        ["7", "Service 91", "5"],
        ["8", "Service 94", "3"],
        ["9", "—", "—"],
    ],
)
pn.note(
    "C-SCAN Total = 4 + 3 + 27 + 22 + 199 + 86 + 5 + 3 = <b>349 tracks</b>\n"
    "Note: The large jump (199) counts as movement but no requests are serviced on the return."
)

pn.section("C-SCAN vs LOOK Comparison")
pn.info_table(
    ["Feature", "C-SCAN", "LOOK (C-LOOK)"],
    [
        [
            "Direction",
            "Sweeps to absolute disk END (track 0 or max)",
            "Sweeps only to the LAST request in current direction",
        ],
        [
            "Return",
            "Jumps from end back to start without servicing",
            "Reverses from last request without going to actual end",
        ],
        [
            "Wait Time",
            "More uniform — processes at one end don't wait longer",
            "Slightly less uniform but shorter sweeps",
        ],
        [
            "Efficiency",
            "Some wasted movement to disk ends",
            "More efficient — no unnecessary movement to end",
        ],
        ["Starvation", "None — all requests serviced in at most 2 sweeps", "None"],
        [
            "Use Case",
            "Classic circular elevator scheduling",
            "Practical improvement used in real disk controllers",
        ],
    ],
)

# -----------------------------------------------------------------------------
#  Q5(e) -- 10 Marks
# -----------------------------------------------------------------------------
pn.chap_box(
    "Q5(e) [10 Marks] -- Free Space Management | Disk Allocation Schemes | Directory Structures\n"
    "(May-June 2024 | July-Dec 2024 | Dec 2022)"
)

pn.section("Free Space Management Techniques")
pn.info_table(
    ["Technique", "How It Works", "Advantages", "Disadvantages"],
    [
        [
            "Bit Vector (Bitmap)",
            "One bit per disk block: 1 = free, 0 = allocated (or vice versa). Bitmap stored in a dedicated area.",
            "Efficient to find first free block or contiguous blocks. Simple implementation.",
            "Bitmap itself takes memory (200 GB disk @ 4 KB blocks = 6.25 MB bitmap). Must keep in memory for efficiency.",
        ],
        [
            "Linked Free List",
            "Free blocks are linked together as a linked list. Head pointer stored by OS.",
            "No wasted space for the list itself (uses the free blocks). Simple insertion/deletion.",
            "Cannot traverse efficiently. Cannot find contiguous free blocks easily. One block per traversal.",
        ],
        [
            "Grouping",
            "First free block stores addresses of N-1 free blocks + pointer to next group block.",
            "Quickly locate many free blocks in one disk access.",
            "Slightly complex management.",
        ],
        [
            "Counting",
            "Instead of listing each free block, store (starting block address, count of contiguous free blocks). Only one entry per contiguous run.",
            "Compact list when many contiguous free blocks exist. Works well after compaction.",
            "List entries vary in meaning; slightly complex.",
        ],
    ],
)

pn.section("Summary: File Allocation Schemes Comparison")
pn.info_table(
    ["Property", "Contiguous", "Linked", "Indexed"],
    [
        ["External Fragmentation", "Yes", "No", "No"],
        ["Internal Fragmentation", "Minimal", "No", "Index block overhead"],
        ["Sequential Access", "Excellent", "Good", "Good"],
        ["Direct Access", "Excellent", "Poor (O(n))", "Excellent"],
        ["File Growth", "Difficult", "Easy", "Easy (up to index size)"],
        ["Reliability", "Good", "Poor (pointer loss)", "Good"],
        ["Used In", "CD-ROM (ISO 9660)", "FAT (Windows)", "Unix inodes, NTFS"],
    ],
)

pn.section("All Directory Structures — Quick Reference")
pn.bullet(
    [
        "<b>Single-Level:</b> All files in one flat namespace. Simple but impractical for multi-user systems.",
        "<b>Two-Level:</b> One directory per user under a master directory. Solves name conflicts between users.",
        "<b>Tree-Structured:</b> Hierarchical. Used by all modern OS (Linux, Windows, macOS). Supports absolute and relative paths.",
        "<b>Acyclic-Graph:</b> Allows sharing via links. Hard links share inode; symbolic links are path references.",
        "<b>General Graph:</b> Allows cycles. Requires garbage collection. Rarely used in practice.",
    ]
)

pn.tip(
    "Exam Summary — Disk Scheduling performance for the given problem: "
    "SSTF (125) &lt; C-SCAN (349) &lt; FCFS (399). "
    "SSTF gives minimum seek time but may cause starvation. "
    "C-SCAN is fair with moderate performance. "
    "FCFS is fair (no starvation) but worst performance."
)

pn.section("Flashcards — Quick Recall")
pn.flashcard(
    "Coffman's 4 Deadlock Conditions",
    "1. Mutual Exclusion. 2. Hold and Wait. 3. No Preemption. 4. Circular Wait. ALL four must hold.",
)
pn.flashcard(
    "Critical Section 3 Requirements",
    "1. Mutual Exclusion. 2. Progress. 3. Bounded Waiting.",
)
pn.flashcard(
    "Banker's Algorithm — Need Formula",
    "Need[i][j] = Max[i][j] − Allocation[i][j]. Safety: find Pi where Need[i] ≤ Work.",
)
pn.flashcard(
    "Page Fault Handling Steps",
    "1. Trap to OS. 2. Find page on disk. 3. Get free frame (evict if needed). 4. Load page. 5. Update PTE. 6. Restart instruction.",
)
pn.flashcard(
    "Disk Scheduling: SSTF vs C-SCAN",
    "SSTF: minimum head movement, starvation possible. C-SCAN: fair, uniform wait, more movement.",
)
pn.flashcard(
    "File Allocation: Contiguous vs Linked vs Indexed",
    "Contiguous: fast access, external frag. Linked: no frag, no direct access. Indexed: best of both.",
)

pn.section("High-Frequency Exam Questions — One-Line Answers")
pn.revision_card(
    "Most Asked Questions — Unit-wise",
    [
        "Q1: Draw the 5-state process diagram with all transition labels.",
        "Q1: Explain 6 categories of system calls with Linux and Windows examples.",
        "Q2: Calculate Avg WT and TAT for FCFS, SJF, RR using the given process table.",
        "Q2: Write the complete semaphore solution for the Bounded Buffer problem.",
        "Q3: Run Banker's Safety Algorithm and find the safe sequence step-by-step.",
        "Q3: Draw RAG showing deadlock (single-instance) and no-deadlock (multi-instance).",
        "Q4: Trace FIFO and LRU page replacement for the given reference string and count faults.",
        "Q4: Explain thrashing with causes and two solutions (Working Set Model, PFF).",
        "Q5: Calculate total head movement for FCFS, SSTF, C-SCAN for the given disk queue.",
        "Q5: Compare all file allocation methods — contiguous, linked, indexed.",
    ],
)

pn.section("All Key Formulas")
pn.info_table(
    ["Formula", "Where Used"],
    [
        ["TAT = Completion Time − Arrival Time",          "All CPU scheduling algorithms"],
        ["WT  = TAT − Burst Time",                        "All scheduling algorithms (non-preemptive)"],
        ["Avg WT = Σ(WT) / N",                            "Compute average waiting time"],
        ["Avg TAT = Σ(TAT) / N",                          "Compute average turnaround time"],
        ["Need[i][j] = Max[i][j] − Allocation[i][j]",    "Banker's Algorithm"],
        ["Physical Addr = Base Register + Logical Addr",  "MMU — contiguous allocation"],
        ["Valid if: Logical Addr < Limit Register",       "MMU protection check"],
        ["EAT = h×(t_TLB+t_mem) + (1−h)×(t_TLB+2t_mem)","TLB Effective Access Time"],
        ["n = λ × W  (Little's Law)",                     "Queuing theory — scheduler evaluation"],
        ["S(N) = 1 / ((1−P) + P/N)  (Amdahl's Law)",     "Parallel speedup with N threads"],
    ],
)


# =============================================================================
#  BUILD OUTPUTS
# =============================================================================
pn.build_doc("OS_PYQ_Answers.pdf")
